openapi: 3.0.2

info:
  title: Users Service
  description: Service serving users
  version: "{{info.version}}"
  contact:
    name: Team Name
    url: https://team.page
    email: team@mailbox
  license:
    name: Proprietary

servers:
  - url: "{{scheme}}://{{host}}{{basePath}}"

tags:
  - name: App Version
  - name: Users
    description: Users CRUD

paths:
  /api/users:
    get:
      tags:
        - Users
      summary: Get paginated list of all users
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            default: 20
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 0
      responses:
        "200":
          description: OK
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersList"
        "400":
          description: Bad Request
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
      responses:
        "201":
          description: Created
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetails"

        "400":
          description: Bad Request
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"

  /api/users/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetails"
        "404":
          description: Not Found
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        "200":
          description: OK
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetails"
        "400":
          description: Bad Request
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not Found
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
    patch:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPatch"
      responses:
        "200":
          description: OK
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetails"
        "400":
          description: Bad Request
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not Found
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"

  /api/users/login={userLogin}:
    get:
      parameters:
        - name: userLogin
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetails"
        "404":
          description: Not Found
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"

  /version:
    get:
      tags:
        - App Version
      summary: Get application version
      responses:
        "200":
          description: OK
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/VersionDetails"

components:
  headers:
    X-Request-ID:
      description: Unique request id. This is either copied from X-Request-ID request header or generated new if not present.
      required: true
      schema:
        type: string
  schemas:
    VersionDetails:
      title: VersionDetails
      type: object
      required:
        - version
      properties:
        version:
          type: string
    UserUpdate:
      title: UserUpdate
      type: object
      required: [name, age]
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
    UserPatch:
      title: UserPatch
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
    UserDetails:
      title: UserDetails
      type: object
      required: [id, login, name, age]
      properties:
        id:
          type: integer
          format: int64
        login:
          type: string
        name:
          type: string
        age:
          type: integer
          format: int32
    NewUser:
      title: NewUser
      type: object
      required: [name, age, login, password]
      properties:
        age:
          type: integer
          format: int32
        login:
          type: string
        name:
          type: string
        password:
          type: string
    UsersList:
      title: UsersList
      type: object
      required: [users]
      properties:
        users:
          title: UsersList
          type: array
          items:
            $ref: "#/components/schemas/UserDetails"
    ApiError:
      title: ApiError
      type: object
      required: [status, type, title, detail, instance, path]
      properties:
        detail:
          type: string
        instance:
          type: string
        path:
          type: string
        status:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
        title:
          type: string
        type:
          type: string
